services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init.sh:/mongodb-init.sh
    networks:
      - app-network
    command: ["bash", "-c", "mongod --replSet rs0 --bind_ip_all & sleep 5 && bash /mongodb-init.sh && tail -f /dev/null" ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5

  postgres:
    image: postgres:latest
    container_name: postgres
    ports: 
     - "5433:5432"
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: openup
      POSTGRES_DB: simple_nestjs_blog
    volumes:
      - postgres_data:/data/db
    networks:
      - app-network

  app:
    build: . 
    container_name: nestjs-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - postgres
    networks:
      - app-network
    environment:
      MONGO_URI: "mongodb://mongodb:27017/nest-blog?replicaSet=rs0"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "openup"
      POSTGRES_DB: "simple_nestjs_blog"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
    mongodb_data: 
    postgres_data: