services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    command: ['mongod', '--replSet', 'rs0']
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  nestjs:
    build: .
    container_name: my_nestjs
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      MONGO_URI: 'mongodb://root:example@mongo:27017/nestjs?authSource=admin&replicaSet=rs0'
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ['sh', '-c', 'npm install && npm run start:dev']
